# Generated by Django 3.1.5 on 2021-01-30 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='qunatity',
            new_name='quantity',
        ),
    ]
